# Generated by Django 5.1.1 on 2024-09-03 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliquery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['user'], name='intelliquer_user_id_4cd7bf_idx'),
        ),
    ]
