# Generated by Django 5.1.1 on 2024-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliquery', '0003_webapp_delete_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapp',
            name='template',
            field=models.CharField(default='index', max_length=10),
        ),
    ]
